Refactor/index changes
EduardoGiacomini/mafcust-backend pull request #16
Opened 2022-05-19 23:14 UTC by F-Camuso

### Overview
Moving permissions and schemas out of the index file

### Pull request type
- [ ] Bug fixes;
- [ ] New feature;
- [X] Refactoring;
- [ ] Documentation;
- [ ] Other: __________________

### Closes: *issues here*

### Current behaviour
There's a lot of functions inside the index file that should have a separated file

### New behaviour

index will be a lot clear now.

The permissions folder will have all the rules and the shield function.

### Additional informations

Its a work in progress...

2022-05-20 00:09 UTC, SantiagoMateus approved these changes

2022-05-20 02:01 UTC, EduardoGiacomini commented
I am thinking about this refactor. Maybe we can broken this `src/index.ts` in some folders and files:

```
- src
    - config (all setups)
        environment.ts (exposes used environment)
        logger.ts (**we need do add a logger to this app**)
    - resolvers (our custom resolvers)
    - generated (auto generated resolvers)
    - application or server (all files to create the server, middlewares, and more)
        - middlewares
        - resolvers (expose resolvers used by application)
        application.ts or server.ts (the class who will create the server app)
        index.ts (only exposes the application/server)
    index.ts (only create a new application/server instance and run the app)
```

What do you think about?

2022-05-23 22:58 UTC, F-Camuso commented
> I am thinking about this refactor. Maybe we can broken this `src/index.ts` in some folders and files:
> 
> ```
> - src
>     - config (all setups)
>         environment.ts (exposes used environment)
>         logger.ts (**we need do add a logger to this app**)
>     - resolvers (our custom resolvers)
>     - generated (auto generated resolvers)
>     - application or server (all files to create the server, middlewares, and more)
>         - middlewares
>         - resolvers (expose resolvers used by application)
>         application.ts or server.ts (the class who will create the server app)
>         index.ts (only exposes the application/server)
>     index.ts (only create a new application/server instance and run the app)
> ```
> 
> What do you think about?

looks good to me, i will work on this after doing the routes

2022-05-24 00:46 UTC, EduardoGiacomini requested changes
Very good

2022-05-24 00:46 UTC, EduardoGiacomini commented on src/config/logger.ts
> +// import { ENVIRONMENT } from './environment';
Opa

2022-05-24 00:46 UTC, EduardoGiacomini commented on src/permissions/index.ts
> +      Logger.info(thrownThing);
Logger.error

2022-05-24 00:46 UTC, EduardoGiacomini commented on src/resolvers/patient-x-exams/CreatePatientXExamsResolver.ts
> +    Logger.info(patientXExams);
debug

2022-05-24 00:46 UTC, EduardoGiacomini commented on src/routes/reports/exams.ts
> +    Logger.info(examCategoryId);
debug

2022-05-24 00:46 UTC, EduardoGiacomini commented on src/routes/reports/index.ts
> +reports.use('/patientsExams', patientsExamsCsv);
lindo

2022-05-24 00:46 UTC, EduardoGiacomini commented on src/routes/reports/patientsExams.ts
> +  Logger.info(singlePatientExams);
debug

2022-05-24 00:46 UTC, EduardoGiacomini commented on src/schema.ts
> +  PatientXIndividualUseCrudResolver,
opa

2022-05-24 22:37 UTC, brunomond approved these changes

2022-05-24 22:38 UTC, merged