New update value report
EduardoGiacomini/mafcust-backend pull request #8
Opened 2022-05-03 00:36 UTC by SantiagoMateus

### Overview
changing unityCost to currentCost in CSV creating and modifying table patientXExams to be relatable to two diferent cost

### Pull request type
- [x] Bug fixes;
- [x] New feature;
- [ ] Refactoring;
- [ ] Documentation;
- [ ] Other: __________________

2022-05-03 01:03 UTC, EduardoGiacomini requested changes
Ao tentar anexar um exame a um paciente eu recebo:

```javascript
[
    {
        "message": "Variable '$data' got invalid value { exams: { connect: [Object] }, patient: { connect: [Object] }, occurrences: 1 }; Field 'currentValue' of required type 'Float!' was not provided."
    }
]
```

Acho que vai ser necessário criar um resolver customizado para pegar o valor do exame e colocar na relação `PatientXExams`.

2022-05-03 23:27 UTC, EduardoGiacomini requested changes

2022-05-03 23:27 UTC, EduardoGiacomini commented on src/resolvers/patient-x-exams/CreatePatientXExamsResolver.ts
> +  }
Problemas de identação

2022-05-03 23:27 UTC, EduardoGiacomini commented on src/resolvers/patient-x-exams/CreatePatientXExamsResolver.ts
> +        const { } = patientXExamsInput;
Remover linha não utilizada.

2022-05-03 23:27 UTC, EduardoGiacomini commented on src/resolvers/patient-x-exams/CreatePatientXExamsResolver.ts
> +          console.log(patientXExams)
Remover `console.log`

2022-05-03 23:27 UTC, EduardoGiacomini commented on src/resolvers/patient-x-exams/CreatePatientXExamsResolver.ts
> +          })
Aqui teremos uma mudança na lógica...

O @brunomond disse que vamos precisar:

Existe o mesmo exame anexado a esse paciente?
----Sim: O exame anexado mais recente possui mudança no valor? *(aqui será necessário verificar se o campo `updatedAt` de exame é mais recente que `createdAt` de patientXExams)*
--------Sim: Anexe um novo exame ao paciente com o valor atualizado.
--------Não: Incremente o número de ocorrências desse exame.
----Não: anexe um novo exame ao paciente com o valor atual do exame.

2022-05-10 01:46 UTC, EduardoGiacomini approved these changes
:rocket:

2022-05-10 22:56 UTC, F-Camuso approved these changes

2022-05-10 23:18 UTC, merged